[tools]
"aqua:go-task/task" = "latest"
"aqua:kdash-rs/kdash" = "latest"
"aqua:mike-engel/jwt-cli" = "latest"
"aqua:txn2/kubefwd" = "latest"
"aqua:vercel-labs/agent-browser" = "latest"
awscli = "latest"
bat = "latest"
copilot-cli = "latest"
deno = "latest"
difftastic = "latest"
dive = "latest"  # Analyze Docker images
duf = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
helm = "latest"
helmfile = "latest"
jq = "latest"
k3d = "latest"
krew = "latest"
kubectl = "latest"
kubectx = "latest"
lazydocker = "latest"
neovim = "latest"
node = "lts"
opencode = "latest"
pipx = "latest"
prettier = "latest"
ripgrep = "latest"
starship = "latest"
yq = "latest"
zoxide = "latest"

[settings]
node.corepack = true
